fix one typo in _helpers.py
Maybe the cause of https://github.com/pygfx/pygfx/issues/938

I'm still getting:
```
Traceback (most recent call last):
  File "/home/mark/miniforge3/envs/dev/lib/python3.10/site-packages/wgpu/gui/_gui_utils.py", line 76, in log_exception
    yield
  File "/home/mark/miniforge3/envs/dev/lib/python3.10/site-packages/wgpu/gui/base.py", line 167, in _draw_frame_and_present
    self.draw_frame()
  File "/home/mark/git/python-owl/owl/gui/_scene_control_gfx.py", line 2464, in animate
    self._renderer.render(
  File "/home/mark/miniforge3/envs/dev/lib/python3.10/site-packages/pygfx/renderers/wgpu/engine/renderer.py", line 536, in render
    container_group = get_pipeline_container_group(wobject, environment)
  File "/home/mark/miniforge3/envs/dev/lib/python3.10/site-packages/pygfx/renderers/wgpu/engine/pipeline.py", line 181, in get_pipeline_container_group
    pipeline_container_group.update(wobject, environment, changed_labels)
  File "/home/mark/miniforge3/envs/dev/lib/python3.10/site-packages/pygfx/renderers/wgpu/engine/pipeline.py", line 261, in update
    container.update(wobject, environment, env_hash, changed)
  File "/home/mark/miniforge3/envs/dev/lib/python3.10/site-packages/pygfx/renderers/wgpu/engine/pipeline.py", line 336, in update
    raise err
  File "/home/mark/miniforge3/envs/dev/lib/python3.10/site-packages/pygfx/renderers/wgpu/engine/pipeline.py", line 333, in update
    self.update_shader_data(wobject, changed)
  File "/home/mark/miniforge3/envs/dev/lib/python3.10/site-packages/pygfx/renderers/wgpu/engine/pipeline.py", line 369, in update_shader_data
    self.update_bind_groups()
  File "/home/mark/miniforge3/envs/dev/lib/python3.10/site-packages/pygfx/renderers/wgpu/engine/pipeline.py", line 464, in update_bind_groups
    binding_des, binding_layout_des = binding.get_bind_group_descriptors(
  File "/home/mark/miniforge3/envs/dev/lib/python3.10/site-packages/pygfx/renderers/wgpu/engine/binding.py", line 134, in get_bind_group_descriptors
    "resource": ensure_wgpu_object(resource),
  File "/home/mark/miniforge3/envs/dev/lib/python3.10/site-packages/pygfx/renderers/wgpu/engine/update.py", line 173, in ensure_wgpu_object
    resource._wgpu_object = wgpu_texture.create_view()
  File "/home/mark/miniforge3/envs/dev/lib/python3.10/site-packages/wgpu/backends/wgpu_native/_api.py", line 2343, in create_view
    id = libf.wgpuTextureCreateView(self._internal, struct)
  File "/home/mark/miniforge3/envs/dev/lib/python3.10/site-packages/wgpu/backends/wgpu_native/_helpers.py", line 384, in proxy_func
    error_type_msg = error_handler.release(name)
  File "/home/mark/miniforge3/envs/dev/lib/python3.10/site-packages/wgpu/backends/wgpu_native/_helpers.py", line 321, in release
    n = self._proxy_stack.pop()
IndexError: pop from an empty deque
```